name: '${project.name}'
description: '${project.description}'
version: '${project.version}'
authors: [HeadMonitor]
website: https://www.playnexia.net/
main: net.nexia.nexiacollection.NexiaCollection
api-version: 1.13